### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by nunojesus** [oldmtn/LiteH5Player#1]
Hello can you give me more informations about this project? Im a graphic designer that contributes for opensource projects like yours, so if you need some help to create a logotype or other stuff just say it.

Greetings

**Comment by nunojesus** [comment]
Can you tell me more about this project, if it is for desktop, android and ios, what colors do you like for the player? Thank you

**Comment by oldmtn** [comment]
It's for browser. I like Green.

**Comment by nunojesus** [comment]
Hello, the name of the player is LiteH5player? or are you thinking in other name?

**Comment by oldmtn** [comment]
Yeah, It is LiteH5Player.

**Comment by nunojesus** [comment]
Hi, for the  concept I pick the letters L and H, the number 5, and I create a player button.

I use lots of greens has you requested.

See if you like it.

![lh5tttt](https://user-images.githubusercontent.com/34600369/40387205-e3d7885c-5e03-11e8-9487-ce119eecdd34.png)

**Comment by oldmtn** [comment]
Do you have a skype?

**Comment by nunojesus** [comment]
Hi, this is the file that you send? I dont understand what do you want? Can you explain me please.

![sem titulo](https://user-images.githubusercontent.com/34600369/40481537-a1fa2100-5f49-11e8-987e-b3487c7bebce.png)

**Comment by oldmtn** [comment]
1. Let the product name be visible.
2. Icon shows the function of the project.
3. 5 shows that the main technology of the project.

**Comment by nunojesus** [comment]
Hi, Im sorry for the late reply, tomorrow I will try to show some designs for your project. Gretings!

**Comment by nunojesus** [comment]
Hello, here are the designs that I create, see if you like one.

![lh5ttttfinal2222](https://user-images.githubusercontent.com/34600369/41492948-8cd52d8e-70fa-11e8-9bb1-b6dffa6bd609.png)

**Comment by oldmtn** [comment]
Oh, That's cool. Thank you.
